name: CloudFormation Security Check

on: [push, pull_request]

jobs:
  security_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 全履歴を取得

      - name: Fetch origin main
        run: git fetch origin main

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install cfn-nag
        run: gem install cfn-nag

      - name: Get diff files
        id: diff
        run: |
          DIFF_FILES=$(git diff --name-only origin/main | grep -E '\.ya?ml$' | grep -v '\.github/workflows/')
          if [ -n "$DIFF_FILES" ]; then
            echo "diff_files=$DIFF_FILES" >> $GITHUB_OUTPUT
            echo "DIFF FILES: $DIFF_FILES" # デバッグ用
          fi

      - name: Run cfn-nag (diff)
        if: steps.diff.outputs.diff_files
        run: |
          echo "cfn-nag-scan input: ${{ steps.diff.outputs.diff_files }}" # デバッグ用
          cfn_nag_scan --input-path ${{ steps.diff.outputs.diff_files }} --deny-list-path ./settings/cfn-nag_deny_list.yml
