name: CloudFormation Security Check

on: [push, pull_request]

jobs:
  security_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install cfn-nag
        run: gem install cfn-nag

      - name: Run cfn-nag
        run: cfn_nag_scan --input-path ./cloudformation-templates/ --deny-list-path ./settings/cfn-nag_deny_list.yml
