name: Manual matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            version: 20
          - os: macos-latest
            version: 18
    runs-on: ${{ matrix.os }}
    steps:
      - uses: action/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: echo "{RUNNER_OS}" %% node --version