name: Environments
on: 
  workflow_dispatch:
    inputs:
      environment-name:
        type: environment
        default: test
        require: false
        description: Environment name
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.output_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: output_matrix
        run: |
          # echo "matrix=$(ls environments | jq -R -s -c '{ "environment": split("\n")[:-1] }')" > $GITHUB_OUTPUT
          #echo "matrix=$(jq -nc --arg envs '${{ env.DEPLOY_ENVIRONMENTS }}' '{ "environment": ($envs | split(" ")) }')" >> $GITHUB_OUTPUT
          MATRIX=$(jq -c '{ "environment": [ .environments[].name ] }')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
  print:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment-name }}
    env:
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${PASSWORD}"